### ISSUE TITLE
I got an error when I used make command in a certain folder in asm

### ISSUE THREAD

**Issue by TroyMitchell911** [plctlab/riscv-operating-system-mooc#10]
### System environment:

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

### GNU Make

GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

### Error

Makefile:1: *** missing separator.  Stop.

### Troubleshooting process

I found that the Makefile files in all folders under asm do not use standard universal syntax, like this:
`../build.mk`

There may be some versions that can support such writing, but there is no doubt that it is not supported on my system. I tried updating make, but it did not work. The general and correct writing should be as follows:
`include ../build.mk`

After making the changes it started working without a doubt

### Ending

Correspondingly, I have sent a PR, I believe it will work well on any make version

**Comment by TroyMitchell911** [comment]
#9

**Comment by unicornx** [comment]
Makefile is just a symbollink to the "../build.mk". It should not be the rootcause of your build problem.

As I know, people met this "Makefile:1: *** missing separator. Stop." because they are working on WSL or copy repo from Windows to Linux. See https://gitee.com/unicornx/riscv-operating-system-mooc/issues/I4OA67.

**Comment by unicornx** [comment]
Assigned back to you. Please double check and close this issue if no more questions.

**Comment by TroyMitchell911** [comment]
Yes, I am working on Ubuntu 22.04 under WSL, but there will be errors if I use it directly. If I add ‘include’, it will work very well, so I still hope you will adopt my PR.
