### ISSUE TITLE
關於 External Interrupt

### ISSUE THREAD

**Issue by ianchen0119** [plctlab/riscv-operating-system-mooc#2]
Hi there!

關於外部中斷，我有一些疑惑，還望各位指教，在介紹第 11 章的外部中斷時，提到了我們可以對 PLIC 設置外部中斷做到 UART 輸入的功能，針對這個地方，我有兩點疑問:
1. 我參考這一資訊，將外部中斷的處理方式移植到了 `mini-riscv-os` 上，但是我發現即使不在 OS 開機時也能使用 UART 輸入，想請問我是不是遺漏了什麼重要觀念
2. 呈上題，如果不開啟外部中斷也能使用 UART 輸入，那在什麼情況下才會產出 `IRQ = 10` 的情況呢?

謝謝。

**Comment by unicornx** [comment]
不好意思，这两天没有及时检查邮件，请问您现在还有问题了么，我看你 close 了这个 issue。

**Comment by ianchen0119** [comment]
@unicornx 我後來已經順利解決了，感謝您的詢問!
